# Generated by Django 4.2 on 2023-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mentor', models.IntegerField()),
                ('id_student', models.IntegerField()),
                ('text_task', models.TextField()),
                ('task_links', models.TextField()),
            ],
        ),
    ]
