# Generated by Django 4.2 on 2023-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmentortostudent',
            name='id_tutor',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
