# Generated by Django 4.2 on 2023-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseChampionship', '0004_auto_20230527_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='file',
            field=models.FileField(upload_to='championship/'),
        ),
    ]
