# Generated by Django 3.2 on 2023-05-27 06:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_applications_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('russian', 'Русский язык'), ('computer', 'Компьютерная граммотность')], max_length=200)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applications')),
            ],
        ),
    ]
