# Generated by Django 4.2.1 on 2023-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_applicationtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='career',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtest',
            name='subject',
            field=models.CharField(choices=[('russian', 'Русский язык'), ('computer', 'Компьютерная граммотность'), ('analysis', 'Анализ информации')], max_length=200),
        ),
    ]
