# Generated by Django 4.2.1 on 2023-05-27 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_applications_career_alter_applicationtest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='career_percent',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='applications',
            name='test_percent',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
