# Generated by Django 4.2.1 on 2023-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_applications_test_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='experience',
            field=models.CharField(choices=[('public activaty', 'Общественная деятельноеть'), ('other', 'Другое')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='education',
            field=models.CharField(choices=[('completed 3rd year bachelor', 'Законьчевший 3 курс бакалавра'), ('completed 4 year bachelor', 'Законьчевший 4 курс бакалавра'), ('master', 'Магистер'), ('higher education', 'высшее образование'), ('other', 'Другое')], max_length=200),
        ),
    ]
