# Generated by Django 4.2.1 on 2023-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_applications_experience_alter_applications_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='experience_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='experience',
            field=models.CharField(choices=[('public activaty', 'Общественная деятельноеть'), ('voluneer', 'Общественная деятельноеть'), ('project activaty', 'Общественная деятельноеть'), ('other', 'Нет опыта работы')], max_length=200, null=True),
        ),
    ]
