# Generated by Django 4.2 on 2023-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230527_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
