# Generated by Django 4.2 on 2023-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_applications_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
